apiVersion: argoproj.io/v2.8
kind: Application
metadata:
  name: myapp-argo-application
  namespace: argocd
spec:
  project: default
source:
  repoURL: https://github.com/furgalaadrian/argo-test-1
  targetRevision: HEAD
  path: dev
destination:
  server: https://kubernetes.default.svc
  namespace: myapp

syncPolicy:
  syncOptions:
    - CreateNamespace=true

  automated:
    #automatycznie ustawia stan taki jak jest w repo, domyślnie te opcje mają ustwaione false
    #selfHeal pozwala tworzyć nowe prune usuwać nie potrzebne i zminieać nazwy
    selfHeal: true
    prune: true
