apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox2
spec:
  selector:
    matchLabels:
      app: busybox2
  replicas: 2
  template:
    metadata:
      labels:
        app: busybox2
    spec:
      containers:
      - name: busybox2
        image: busybox:1.36
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
