apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp3
spec:
  selector:
    matchLabels:
      app: myapp3
  replicas: 1
  template:
    metadata:
      labels:
        app: myapp3
    spec:
      containers:
      - name: myapp3
        image: busybox:1.36
        args:
        - sleep
        - "1000"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
